name: Lighthouse Audit
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # checkout this repo, so you can run an 'npm install'
      # - run: npm install # needed to install your Lighthouse Plugin
      # - run: npm install lighthouse # install missing Lighthouse, this is currently a hack
      # - run: mv node_modules/lighthouse-plugin-social-sharing . # move the Lighthouse plugin one folder upward, this is currently a hack,
      - run: npm install
      # - run: mv node_modules/lighthouse-plugin-social-sharing /home/runner/work/_actions/treosh/lighthouse-ci-action/v2/node_modules
      # - run: ls -a
      # - run: ls node_modules
      # - run: echo $(pwd)/node_modules
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        env:
          NODE_PATH: /home/runner/work/lighthouse-plugin-sample-project/lighthouse-plugin-sample-project/node_modules
        with:
          urls: |
            https://lighthouse-plugin-sample-project.glitch.me/
          configPath: ./lighthouserc.json
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files