name: Lighthouse Audit
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1 # checkout this repo, so you can run an 'npm install'
      # - run: npm install # needed to install your Lighthouse Plugin
      # - run: npm install lighthouse # install missing Lighthouse, this is currently a hack
      # - run: mv node_modules/lighthouse-plugin-social-sharing . # move the Lighthouse plugin one folder upward, this is currently a hack,
      - run: npm install
      - run: ls -a
      - run: ls node_modules
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://lighthouse-plugin-sample-project.glitch.me/
          configPath: ./lighthouserc.json
          env:
            NODE_ENV: node_modules
      - run: ls -a
      - name: Save results
        uses: actions/upload-artifact@v1
        with:
          name: lighthouse-results
          path: '.lighthouseci' # This will save the Lighthouse results as .json files